spring:
    profiles:
        active: local
    devtools:
        add-properties: false
    jpa:
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create
        open-in-view: false
                

    flyway:
        check-location: false