-- Drop All tables
drop table if exists area;
drop table if exists place;
drop table if exists reply;
drop table if exists setting;
drop table if exists tag;

-- Create All tables;
CREATE TABLE area (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) NULL,
	create_dt timestamp NULL,
	update_dt timestamp NULL,
	CONSTRAINT area_pkey PRIMARY KEY (id)
);

CREATE TABLE place (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NULL,
	addr varchar(255) NULL,	
	phone varchar(255) NULL,
	description varchar(255) NULL,
	rate int4 NULL,
	visit_dt timestamp NULL,
	create_dt timestamp NULL,
	update_dt timestamp NULL,
	CONSTRAINT place_pkey PRIMARY KEY (id)
);

CREATE TABLE reply (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"text" varchar(255) NULL,
	create_dt timestamp NULL,
	update_dt timestamp NULL,
	CONSTRAINT reply_pkey PRIMARY KEY (id)
);

CREATE TABLE setting (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	code varchar(255) NULL,
	value varchar(255) NULL,
	create_dt timestamp NULL,
	update_dt timestamp NULL,
	CONSTRAINT setting_pkey PRIMARY KEY (id)
);

CREATE TABLE tag (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(255) NULL,
	create_dt timestamp NULL,
	update_dt timestamp NULL,
	CONSTRAINT tag_pkey PRIMARY KEY (id)
);