-- Drop All tables
drop table area if exists;
drop table place if exists;
drop table reply if exists;
drop table setting if exists;
drop table tag if exists;

-- Create All tables;
CREATE TABLE area (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	create_dt timestamp NULL,
	update_dt timestamp NULL,
	name varchar(255) NULL,
	CONSTRAINT area_pkey PRIMARY KEY (id)
);

CREATE TABLE place (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	create_dt timestamp NULL,
	update_dt timestamp NULL,
	addr varchar(255) NULL,
	description varchar(255) NULL,
	"name" varchar(255) NULL,
	phone varchar(255) NULL,
	rate int4 NULL,
	visit_dt timestamp NULL,
	CONSTRAINT place_pkey PRIMARY KEY (id)
);

CREATE TABLE reply (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	create_dt timestamp NULL,
	update_dt timestamp NULL,
	"text" varchar(255) NULL,
	CONSTRAINT reply_pkey PRIMARY KEY (id)
);

CREATE TABLE setting (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	create_dt timestamp NULL,
	update_dt timestamp NULL,
	code varchar(255) NULL,
	value varchar(255) NULL,
	CONSTRAINT setting_pkey PRIMARY KEY (id)
);

CREATE TABLE tag (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	create_dt timestamp NULL,
	update_dt timestamp NULL,
	"name" varchar(255) NULL,
	CONSTRAINT tag_pkey PRIMARY KEY (id)
);